name: Python Coverage Report

on:
  push:
    branches:
      - main  # или другая ветка, на которой вы хотите запускать CI
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest  # или другой доступный образ, например, windows-latest

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: 5432

    steps:
    # Шаг 1: Настройка Python
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Укажите вашу версию Python

    # Шаг 2: Установка зависимостей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # обновление pip
        pip install -r $GITHUB_WORKSPACE/requirements.txt     # установка зависимостей из requirements.txt
        pip install pytest pytest-cov       # установка pytest и плагина для покрытия

    # Шаг 3: Запуск тестов с покрытием
    - name: Run tests with coverage
      run: |
        pytest --cov=shop_API_service tests/  # замените на имя вашего проекта и путь к тестам

    # Шаг 4: Отправка отчета на Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # секретный токен Codecov
